---
- hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: latest

    - name: Install PHP and required extensions
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: latest

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: true


    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted