---
- name: deploying apache2 and redhat 
  hosts: website
  become: yes
  tasks: 
    - name: installing apache2 on ubuntu server
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"    
    - name: insuring apache is running and if not started
      ansible.builtin.systemd_service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "Debian"    
    - name: installing apache2 in redhat server
      ansible.builtin.dnf:
        name: httpd
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "RedHat"    
    - name: enabling apache is runing and started if not
      ansible.builtin.systemd_service:
        name: httpd
        enabled: yes
        state: started                   
      when: ansible_facts['os_family'] == "RedHat"    


---

---
- name: install apache server on redhat
  hosts: website
  become: yes
  tasks:
    - name: install apache server on redhat
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: ensure apache service is running
      ansible.builtin.systemd_service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "RedHat"
    - name: install apache server on ubuntu 
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: ensure apache service is running 
      ansible.builtin.systemd_service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "Debian"
