---
- name: deploying a sping petclinic application on redhat
  hosts: appserver
  become: yes
  gather_facts: yes
  tasks:
    - name: i will not run this application other than ubuntu
      ansible.builtin.fail:
        msg: "you are not allowed to run this application other than ubuntu"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: downloading a open jdk
      ansible.builtin.apt:
        name: openjdk-17-jdk 
        update_cache: yes
        enable: yes
        state: present
    - name: creating a user 
      ansible.builtin.user:
        name: spc
        shell: /bin/sh
        state: "present"
        create_home: yes
        home: '/var/lib/spc' 
    - name: download the jar file into a specfic loaction
      ansible.builtin.url:
        url: "https://referenceappslt.s3.ap-south-1.amazonaws.com/spring-petclinic-3.3.0-SNAPSHOT.jar"
        dest: '/var/lib/spc/spring-petclinic-3.3.0-SNAPSHOT.jar'
        owner: spc
    - name: copy the service file
      ansible.builtin.copy:
        src: spc.service
        dest: /usr/lib/systemd/system/spc.service
    - name: reload daemon, enable and start spc
      ansible.builtin.systemd_service:
        name: spc
        daemon_reload: yes
        enabled: yes
        state: started     